#!/usr/bin/env bash
# Displays information about subdomains
get_info()
{
    rec=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $4;}')
    ip=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $5;}')
}
if [ $# -eq 1 ]
then
    for sub in "www" "lb-01" "web-01" "web-02"; do
	get_info "$1"
	echo "The subdomain $sub is a $rec record and points to $ip"
    done
fi

if [ $# -eq 2 ]
then
    sub=$2
    get_info "$1"
    echo "The subdomain $sub is a $rec record and points to $ip"
fi
