#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# and only displayes username, group id and shell full path for user

while read -r; do
      echo "$REPLY" | cut -d ':' -f1,3,6;
      done < /etc/passwd