#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# and only displayes username, group id and shell full path for user

while read line; do
      echo "$line" | cut -d ':' -f 1,3,6
done < /etc/passwd