#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times and Hi once

i=0
while [ $i -lt 10 ]; do
       if [ "$i" -eq "9" ]; then echo Hi; fi
       echo Holberton School; (( i++ )); done
