#!/usr/bin/env bash
# script to setup nginx and create a custom HTTP header
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i '16 i\        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
