#!/usr/bin/env bash
#Run Nginx as user nginx
sudo pkill -f apache2
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod 777 ../nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' ../nginx.conf
sudo service nginx restart
